package org.coding.parkinglot.domain;

import org.coding.common.annotation.Nullable;

import java.util.Objects;
import java.util.Optional;
import java.util.StringJoiner;

public class Slot {
    @Nullable
    private Integer id;
    private ParkingFloor floor;
    private int type;

    // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    public Slot(@Nullable Integer id, ParkingFloor floor, int type) {
        this.id = id;
        this.floor = Objects.requireNonNull(floor);
        this.type = type;
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    public Optional<Integer> getId() {
        return Optional.ofNullable(id);
    }

    public void setId(@Nullable Integer id) {
        this.id = id;
    }

    public ParkingFloor getFloor() {
        return floor;
    }

    public void setFloor(ParkingFloor floor) {
        this.floor = Objects.requireNonNull(floor);
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Slot that = (Slot) o;

        return Objects.equals(this.getId(), that.getId()) && Objects.equals(this.getFloor(), that.getFloor()) && Objects.equals(this.getType(), that.getType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getFloor(), getType());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("id=" + getId())
//                .add("floor=" + getFloor())
                .add("type=" + getType())
                .toString();
    }// endregion toString()
    // endregion Constructor, getters, setters, equals, hashCode, toString
}
