package org.coding.common.error;

import org.coding.common.annotation.Nullable;

import java.util.*;

public class ErrorCollection {
    @Nullable
    private List<Error> errors;
    private String errorMessage;

    // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    public ErrorCollection(@Nullable Collection<Error> errors, String errorMessage) {
        this.errors = errors != null ? new ArrayList<>(errors) : null;
        this.errorMessage = Objects.requireNonNull(errorMessage);
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    public Optional<List<Error>> getErrors() {
        return Optional.ofNullable(errors);
    }

    public void setErrors(@Nullable List<Error> errors) {
        this.errors = errors != null ? new ArrayList<>(errors) : null;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = Objects.requireNonNull(errorMessage);
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ErrorCollection that = (ErrorCollection) o;

        return Objects.equals(this.getErrors(), that.getErrors()) && Objects.equals(this.getErrorMessage(), that.getErrorMessage());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getErrors(), getErrorMessage());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("errors=" + getErrors())
                .add("errorMessage=" + getErrorMessage())
                .toString();
    }// endregion toString()
    // endregion Constructor, getters, setters, equals, hashCode, toString
}
